; song ids
; Music indexes (see audio/music_pointers.asm)
	const_def
	const MUSIC_NONE
	const MUSIC_OPENING
	const MUSIC_INTRO
	const MUSIC_RIVAL
	const MUSIC_ROUTE_201
	const MUSIC_LAKE
	const MUSIC_WILD_BATTLE
	const MUSIC_WILD_VICTORY
	const MUSIC_SANDGEM_TOWN
	const MUSIC_FOLLOW_ME
	const MUSIC_POKEMON_CENTER
	const MUSIC_HEAL
	const MUSIC_TRAINER_BATTLE
	const MUSIC_TRAINER_VICTORY
	const MUSIC_JUBILIFE_CITY
	const MUSIC_ROUTE_203
	const MUSIC_RIVAL_BATTLE
	const MUSIC_OREBURGH_CITY
	const MUSIC_GYM
	const MUSIC_GYM_LEADER_BATTLE
	const MUSIC_GYM_VICTORY
	const MUSIC_ROUTE_205
	const MUSIC_GALACTIC_BATTLE
	const MUSIC_ETERNA_FOREST
	const MUSIC_GALACTIC_ADMIN_BATTLE
	const MUSIC_EVOLUTION
	const MUSIC_BICYCLE
	const MUSIC_ROUTE_206
	const MUSIC_ROUTE_209
	const MUSIC_SOLACEON_TOWN
	const MUSIC_ROUTE_210
	const MUSIC_CANALAVE_CITY
	const MUSIC_ROUTE_216
	const MUSIC_CYRUS_BATTLE
	const MUSIC_DIALGA_BATTLE
	const MUSIC_SUNYSHORE_CITY
	const MUSIC_ROUTE_225
	const MUSIC_ROUTE_228
	const MUSIC_TV_STATION
	const MUSIC_SURF
	const MUSIC_UNDERGROUND
	const MUSIC_GAME_CORNER
	const MUSIC_MESPRIT_BATTLE
	const MUSIC_POKERADAR
	const MUSIC_POFFINS
	const MUSIC_STARK_MOUNTAIN
	const MUSIC_CHAMPION_ENCOUNTER
	const MUSIC_CHAMPION_BATTLE
DEF NUM_MUSIC_SONGS EQU const_value

; ExitPokegearRadio_HandleMusic uses these values
DEF RESTART_MAP_MUSIC EQU $fe
DEF ENTER_MAP_MUSIC   EQU $ff

; GetMapMusic picks music for this bit flag
	const_def 7
	shift_const RADIO_TOWER_MUSIC
assert NUM_MUSIC_SONGS <= RADIO_TOWER_MUSIC, "song IDs overlap RADIO_TOWER_MUSIC"
