; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	table_width 3
	dba Music_Nothing
	dba Music_Opening
	dba Music_Intro
	dba Music_Rival
	dba Music_Route201
	dba Music_Lake
	dba Music_SinnohWildBattle
	dba Music_WinPokeSinnoh
	dba Music_Sandgem
	dba Music_FollowMe
	dba Music_PokemonCenter
	dba Music_HealPokemon
	dba Music_SinnohTrainerBattle
	dba Music_WinTrainerSinnoh
	dba Music_JubilifeCity
	dba Music_Route203
	dba Music_RivalBattle
	dba Music_Oreburgh
	dba Music_SinnohGym
	dba Music_SinnohGymBattle
	dba Music_WinGymSinnoh
	dba Music_Route205
	dba Music_GalacticBattle
	dba Music_EternaForest
	dba Music_GalacticAdminBattle
	dba Music_Evolution
	dba Music_SinnohBike
	dba Music_Route206
	dba Music_Route209
	dba Music_Solaceon
	dba Music_Route210
	dba Music_Canalave
	dba Music_Route216
	dba Music_CyrusBattle
	dba Music_DialgaBattle
	dba Music_SunyShore
	dba Music_Route225
	dba Music_Route228
	dba Music_TVStation
	dba Music_SinnohSurfing
	dba Music_Underground
	dba Music_SinnohGameCorner
	dba Music_MespritBattle
	dba Music_PokeRadar
	dba Music_Poffins
	dba Music_StarkMountain
	dba Music_LookChampion
	dba Music_ChampionBattle
	assert_table_length NUM_MUSIC_SONGS
